# Generated by Django 4.2.1 on 2023-05-23 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recurso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('plano', models.CharField(max_length=100, verbose_name='Plano')),
                ('preco', models.CharField(max_length=100, verbose_name='Preço')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('icon', models.CharField(choices=[('lni-package', 'Pacote'), ('lni-drop', 'Gota'), ('lni-star', 'Estrela')], max_length=12, verbose_name='Icone')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
            },
        ),
    ]
