# Generated by Django 4.2.1 on 2023-05-23 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_testemunha1_delete_testemunha'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testemunha1',
            new_name='Testemonial',
        ),
    ]
