# Generated by Django 4.2.1 on 2023-05-24 19:11

import core.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_feedback_delete_testemonial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Feedback'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 75, 'width': 75}}, verbose_name='Imagem'),
        ),
    ]
